using System.ComponentModel.DataAnnotations;

namespace hongWenAPP.Models.InvoiceModel.DTOs
{
    // Get Invoice DTO (List)
    public class GetInvoiceDTO
    {
        public Guid InvoiceId { get; set; }
        public string InvoiceNumber { get; set; } = string.Empty;
        public Guid StudentId { get; set; }
        public string StudentCode { get; set; } = string.Empty;
        public string StudentName { get; set; } = string.Empty;
        public Guid StudentCourseId { get; set; }
        public string CourseName { get; set; } = string.Empty;
        public Guid TermId { get; set; }
        public string TermName { get; set; } = string.Empty;
        public DateTime InvoiceDate { get; set; }
        public DateTime DueDate { get; set; }
        public decimal Subtotal { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal LateFeeAmount { get; set; }
        public decimal AdjustmentAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal AmountOutstanding { get; set; }
        public decimal CreditApplied { get; set; }
        public string Status { get; set; } = string.Empty;
        public string InvoiceType { get; set; } = string.Empty;
        public bool IsAutogenerated { get; set; }
        public int LineItemCount { get; set; }
        public DateTime CreateDate { get; set; }
    }

    // Get Invoice Detail DTO
    public class GetInvoiceDetailDTO
    {
        public Guid InvoiceId { get; set; }
        public string InvoiceNumber { get; set; } = string.Empty;
        public Guid StudentId { get; set; }
        public string StudentCode { get; set; } = string.Empty;
        public string StudentName { get; set; } = string.Empty;
        public string CourseName { get; set; } = string.Empty;
        public string TermName { get; set; } = string.Empty;
        public DateTime InvoiceDate { get; set; }
        public DateTime DueDate { get; set; }
        public string Status { get; set; } = string.Empty;
        public string InvoiceType { get; set; } = string.Empty;
        public decimal Subtotal { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal LateFeeAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal AmountOutstanding { get; set; }
        public List<InvoiceLineItemDTO> LineItems { get; set; } = new List<InvoiceLineItemDTO>();
        public List<InvoicePaymentDTO> Payments { get; set; } = new List<InvoicePaymentDTO>();
        public string? Notes { get; set; }
    }

    // Invoice Line Item DTO
    public class InvoiceLineItemDTO
    {
        public Guid InvoiceDetailId { get; set; }
        public string ItemType { get; set; } = string.Empty;
        public Guid? ItemId { get; set; }
        public string? ItemCode { get; set; }
        public string ItemName { get; set; } = string.Empty;
        public string? Description { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal LineTotal { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsFromClass { get; set; }
    }

    // Invoice Payment Summary
    public class InvoicePaymentDTO
    {
        public Guid PaymentId { get; set; }
        public string PaymentReference { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
    }

    // Add Line Item DTO
    public class AddInvoiceLineItemDTO
    {
        [Required]
        public string ItemType { get; set; } = string.Empty;

        public Guid? ItemId { get; set; }

        public string? ItemCode { get; set; }

        [Required]
        public string ItemName { get; set; } = string.Empty;

        public string? Description { get; set; }

        public int Quantity { get; set; } = 1;

        [Required]
        public decimal UnitPrice { get; set; }

        public bool IsMandatory { get; set; } = false;
    }

    // Apply Discount DTO
    public class ApplyDiscountDTO
    {
        public decimal DiscountAmount { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string DiscountReason { get; set; } = string.Empty;
        public string? ModifiedBy { get; set; }
    }

    // Outstanding Balance DTO
    public class OutstandingBalanceDTO
    {
        public Guid StudentId { get; set; }
        public decimal TotalOutstanding { get; set; }
        public decimal OverdueAmount { get; set; }
        public decimal CurrentDue { get; set; }
        public int OverdueInvoices { get; set; }
        public int PendingInvoices { get; set; }
    }
}

